services:
  ims_db:
    image: mysql:8.0
    container_name: ims_db_container
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ims_finance
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ims_web:
    build: 
      context: ./IMSApp
      dockerfile: Dockerfile
    container_name: ims_blazor_container
    ports:
      - "5000:80"
    depends_on:
      - ims_db
    environment:
      - ConnectionStrings__DefaultConnection=Server=ims_db;Database=ims_finance;Uid=root;Pwd=password123;